### ISSUE TITLE
新しくついかしてみました

### ISSUE THREAD

**Issue by arayada** [petergius/CentOs_Clock#2]
さっとみたらクローズよろしくです

**Comment by arayada** [comment]
画面右側の、Assigneesをペテルギウスにしてみてください
プロジェクトをCent_OSに変えてみてください

**Comment by arayada** [comment]
クローズは、とりあえずやらないように！！！！

**Comment by petergius** [comment]
やってみました！

**Comment by petergius** [comment]
issueへの紐づけ確認が完了したのでクローズ
